services:
  billing-platform:
    container_name: 'billing-platform-api'
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - billing-platform
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${DATABASE_URI}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mongodb:
    container_name: 'billing-platform-db'
    image: mongo:latest
    networks:
      - billing-platform
    env_file:
      - .env
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    restart: unless-stopped

  redis:
    container_name: 'billing-platform-redis'
    image: redis:latest
    networks:
      - billing-platform
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - redis-data:/data/redis
    restart: unless-stopped

volumes:
  mongodb-data:
  redis-data:

networks:
  billing-platform:
