services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${DATABASE_URI}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    restart: unless-stopped

  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    restart: unless-stopped

volumes:
  mongodb-data:
